<?php

return array (
  'name' => 'Uwebadmin',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.4.5',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'system' => 'Config',
    'expert' => 'ExpertOnline',
    'category' => '专家/配方/知识库分类',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.163.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '',
  'mail_smtp_pass' => '',
  'mail_verify_type' => '2',
  'mail_from' => '',
  'keywords' => 'Uwebadmin',
  'description' => 'Uwebadmin',
  'seo_title' => '表面处理联盟  技术·配方·咨询',
  'seo_keywords' => ' 表面处理联盟    说化有益   前处理     表面化学    电镀技术    磷化技术   表面处理网   表面处理联盟网  中国表面处理网  洗涤原料    洗涤剂原料   前处理配方   表面处理工程师  表面处理   专家在线   免费发布信息    陶化剂配置方法   前处理网    表面活性剂网    除蜡水   除油粉    电镀添加剂   磷化液配方   研磨剂配方  ',
  'seo_description' => '表面处理技术咨询.前处理配方.化工百科.知识培训.产品信息发布.原材料供应.表面处理人才招聘.实体与互联网的创新集合体',
  'online_one_price' => '1',
  'online_two_price' => '1',
  'online_three_price' => '1.5',
  'locale_one_price' => '50',
  'locale_two_price' => '100',
  'locale_three_price' => '150',
  'gold_num' => '100',
  'service_charge' => '0.3',
  'today_login_num' => '16580',
  'today_question_num' => '2',
  'sensitive' => '毛泽东|邓小平|最好|习近平|第一|首位|毒品（含毒品原料）|最先进|赌博博彩用具|绝对|最高级|最佳|首个|首选|首发|最高|最低|最具|最便宜|最新技术|独家|全网销量|世界领先|独一无二|麻黄素|伪麻黄素|消旋麻黄素|去甲麻黄素|甲基麻黄素|麻黄浸膏|麻黄浸膏粉|麦角新碱|麦角酸|1－苯基－2－丙酮|胡椒醛|麦角胺|３，4－亚甲基二氧苯基－2－丙酮|黄樟素（黄樟油）|异黄樟素|异黄樟素|苯基|丙酮|N－乙酰邻氨基苯酸|邻氨基苯甲酸|羟亚胺|苯乙酸|醋酸酐|三氯甲烷|乙醚|哌啶|甲苯|甲基乙基酮|熊胆|熊胆制品|熊胆酒|熊胆药品|熊胆保健食品|毒品|鸦片|吗啡|海洛因|大麻|杜冷丁|古柯|可卡因|冰毒|摇头丸|K粉|咖啡因|三唑仑|兴奋剂|盐酸羟亚胺|盐酸氯胺酮|盐酸麻黄素|美沙酮|枪支配件|弹药|仿真枪|枪械|枪械仿制品|子弹|炮弹|枪支瞄准器|消音器|麻醉注射枪|射机枪|易燃物品|易爆物品|有毒物品|火药|炸药|雷管|刀|军|国徽|火棉|砒霜|氰化钠|氰化钾|制毒化学品|致隐性药物|美沙酮|阿片酊|氢氧化钠|氨水|敌敌畏|碘化汞',
  'points_num' => '100',
  'expert_ica' => '表面活性剂--碱性清洗剂--除油粉--除油剂--除蜡水--研磨剂--除蜡粉--玻璃清洗剂--酸性清洗剂',
  'expert_tsf' => '硅烷--陶化--锌系磷化--铁系磷化--皮膜--防腐--防锈--铝皮膜--锌皮膜--合金皮膜--钝化--抛光--漂白--喷砂--抗氧化--金属发黑',
  'expert_pp' => '喷涂--电镀--电泳--喷漆--喷油--氧化--真空电镀--喷粉',
  'formula_ica' => '除油粉--碱性清洗剂--化学除油粉--电解除油粉--电镀除油粉--除油剂--除蜡水--除蜡粉--玻璃清洗剂--酸性清洗剂--除锈--防锈--切削液--除灰剂--研磨剂--光泽剂--除油剂--除锈剂--日化清洗--铜抛光--电化学抛光',
  'formula_tsf' => '硅烷--陶化--磷化--皮膜--防腐--防锈--发黑剂--钝化--漂白--喷砂--氧化--铝皮膜--阳极氧化--抗氧化--发黑',
  'formula_pp' => '喷粉--电镀--电泳--喷漆--喷油--喷砂--氧化--真空电镀',
  'konwledge_ica' => '表面活性剂--无机盐--碱性清洗剂--除油粉--除油剂--除蜡水--研磨剂--光亮剂--除蜡--玻璃清洗剂--酸性清洗剂--HLB值--防锈--防腐剂--包装桶--机械设备--除灰剂--光泽剂--切消液--除锈剂',
  'konwledge_tsf' => '硅烷--陶化--磷化--铝皮膜--防腐--防锈--锌皮膜--合金--皮膜--钝化--抛光--漂白--喷砂--抗氧化--发黑',
  'konwledge_pp' => '喷粉--电镀--电泳--喷漆--喷油--镀锌--镀镍--镀金--镀铜--氧化',
  'min_money' => '50',
  '1_online_price' => '1.5',
  '2_online_price' => '1.5',
  '3_online_price' => '2',
  'register_gold_sum' => '0',
  'formula_konwledge_source' => '表面处理联盟',
  'all_question_text' => '&lt;p class=&quot;left-sum-p&quot;&gt;1.您的问题所有工程师/专家可见、可抢答！&lt;/p&gt;&lt;p class=&quot;left-sum-p&quot;&gt;2.为了快速抢答您的问题，问题内容尽量详细！&lt;/p&gt;&lt;p class=&quot;left-sum-p&quot;&gt;3.技术含量较高可附上图片或适当重赏！&lt;/p&gt;',
  'mobile_all_question_text' => '&lt;div class=&quot;list&quot;&gt;1. &lt;span style=&quot;white-space:normal;&quot;&gt;您的问题所有工程师/专家可见、可抢答！&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;list&quot;&gt;2. &lt;span style=&quot;white-space:normal;&quot;&gt;为了快速抢答您的问题，问题内容尽量详细！&lt;/span&gt;&lt;/div&gt;&lt;div class=&quot;list&quot;&gt;3. &lt;span style=&quot;white-space:normal;&quot;&gt;技术含量较高可附上图片或适当重赏！&lt;/span&gt;&lt;/div&gt;',
  'article_pay_num' => '0',
);